# 04-backend-user-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-user
spec:
  type: NodePort
  selector:
    app: backend-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3020
      nodePort: 30020
