apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dalmofelipe/qc-frontend-alpine:0.1.2-staging
        ports:
        - containerPort: 80

# nao tem ordem definida, entre deployments e services
# metadate = service
# spec = pods
# kubectl apply -f 02-frontend-deployment.yaml -n staging
