# 07-backend-scm-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-scm
spec:
  type: NodePort
  selector:
    app: backend-scm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
      nodePort: 30030
